### ISSUE TITLE
Twitter App

### ISSUE THREAD

**Issue by alex9552** [alex9552/Twitter#1]
/cc @codepathreview

**Comment by tuhoag** [comment]
It does not appear that you have added a README file to your Repo. Please add a README file, and use the README template to fill out the README. Be sure to also include an animated gif in your README to show a demo of your finished app. When properly linked, the gif should render (animate) within your README file. 

Your assignment needs to be updated within 24hrs in order for you to receive credit for this assignment.

**Comment by chieger** [comment]
Alex,

It looks like you have almost the entire assignment completed! 

As mentioned in the comment above, you need to add a README and an animated gif of your app.

Note: The following user story has been made optional, so you just need to have all the user stories that are included in the video.

> Retweeting and favoriting should increment the retweet and favorite count.

This needs to be finished by the 11:59pm tonight if you want to remain as a participant in the course. Otherwise, you can continue as an observer where you will have access to course materials but not participate in in-person classes, support channels or the group project.

Please let me know how you wish to proceed.

Charlie Hieger
CodePath University Dean

**Comment by alex9552** [comment]
Sorry about that @hatu87  @chieger 
It is updated with the correct files now
